# Generated by Django 6.0.6 on 2026-07-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("sku", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("current_stock", models.IntegerField(default=0)),
                ("purchase_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="products_pr_name_9ff0a3_idx"),
                    models.Index(fields=["sku"], name="products_pr_sku_ca0cdc_idx"),
                ],
            },
        ),
    ]
